# AxportalBackend API 서버 기본 설정

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Spring 기본 설정
spring:
  application:
    name: axportal-backend
  
  profiles:
    active: local
  
  # JPA 기본 설정
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        ddl-auto: create-drop

  # Jackson 설정
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  # 캐시 설정
  cache:
    type: simple

# CORS 기본 설정 (환경별로 오버라이드 가능)
cors:
  allowed-origins: "http://localhost:3000,http://localhost:8080,https://localhost:3000"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD"
  allowed-headers: "*"
  exposed-headers: "Authorization,Content-Type,X-Total-Count,X-Page-Count,X-User-Id,X-Trace-Id"
  allow-credentials: true
  max-age: 3600

# 로깅 설정
logging:
  level:
    com.skax.aiplatform: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

# OpenAPI 문서 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# JWT 설정
jwt:
  secret: your-secret-key-change-this-in-production
  expiration: 86400000 # 24시간 (밀리초)
  refresh-expiration: 604800000 # 7일 (밀리초)

# 애플리케이션 특정 설정
app:
  name: AxportalBackend
  version: 1.0.0
  description: Spring Boot 기반의 AI Portal RESTful API
