# 외부 개발 환경 설정 (PostgreSQL)

spring:
  # PostgreSQL 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/axportal_edev
    driver-class-name: org.postgresql.Driver
    username: axportal_user
    password: axportal_password
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

# 로깅 레벨
logging:
  level:
    root: INFO
    com.skax.aiplatform: DEBUG
