# 외부 Local 환경 설정 (H2 인메모리 데이터베이스)

spring:
  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:axportal_elocal;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# SpringDoc OpenAPI 설정
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
  show-actuator: true


# JWT 설정
jwt:
  secret: myDevSecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLongForSecurityPurposes
  access-token-validity-in-seconds: 3600    # 1시간
  refresh-token-validity-in-seconds: 604800 # 7일

# CORS 설정 (개발 환경용 - 모든 오리진 허용)
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD"
  allowed-headers: "*"
  exposed-headers: "Authorization,Content-Type,X-Total-Count,X-Page-Count,X-User-Id,X-Trace-Id"
  allow-credentials: true
  max-age: 86400

# 로깅 레벨
logging:
  level:
    root: INFO
    com.skax.aiplatform: DEBUG
