# 외부 Local 환경 설정 (H2 인메모리 데이터베이스)

spring:
  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:axportal_elocal;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# 로깅 레벨
logging:
  level:
    root: INFO
    com.skax.aiplatform: DEBUG
